server:
  # Database configuration
  database:
    host: localhost
    port: 5432
    username: cao
    password: cao
    database: cao
  
  # Web-server configuration
  web:
    host: 0.0.0.0
    port: 1234

client:
  enable_wizz: true         # Whether players can use the "wizz" from MSN