services:
  database:
    image: postgres:14-alpine
    ports: [ 5432:5432 ]
    environment:
      POSTGRES_USER: cao
      POSTGRES_PASSWORD: cao
      POSTGRES_DB: cao
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  frontend:
    image: node:16-alpine
    ports: [3050:3000]
    working_dir: /app
    command: ['ash', '-c', '[ ! -d node_modules ] && npm install; npm run dev']
    volumes:
      - ./frontend:/app
    extra_hosts:
      - host.docker.internal:host-gateway